[package]
name = "LogBurst"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
axum-extra = { version = "0.10.1", features = ["typed-header"] }
headers = "0.4.0"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1.44.2", features = ["full"] }
async-trait = "0.1.88"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.97"
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
once_cell = "1.21.3"
log = "0.4.27"
env_logger = "0.11.8"
thiserror = "2.0.12"
ring = { version = "0.17.14", features = ["std"] }
hex = "0.4.3"
clickhouse = "0.13.2"