services:
  pg:
    container_name: pg
    image: postgres:17.0
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init/pg:/docker-entrypoint-initdb.d

  clickhouse-server:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server:25.4.2.31
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "8000:9000"
    env_file:
      - .env
    volumes:
      - ./init/clickhouse:/docker-entrypoint-initdb.d
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server

  log-service:
    container_name: log-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8383:${SERVICE_PORT}"
      - "8081:8081"
    environment:
      - RUST_LOG=info
    depends_on:
      - pg
      - clickhouse-server

volumes:
  clickhouse-data:
  clickhouse-logs: